/* TalentKenya offer letter PDF generator — branded, formatted offer letter
   downloadable by candidates and employers. Uses jsPDF with the brand green
   palette (#166534) and Garamond-style serif/sans pairing. */
import { jsPDF } from "jspdf";
import { type Offer } from "./platform";

const GREEN: [number, number, number] = [22, 101, 52];
const DARK: [number, number, number] = [23, 23, 23];
const GRAY: [number, number, number] = [100, 100, 100];
const LIGHT: [number, number, number] = [228, 242, 233]; // light green for table header

export function generateOfferLetterPdf(o: Offer, candidateName: string) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = 210;
  const margin = 20;
  const contentW = W - margin * 2;
  let y = margin;

  // ── Header band
  doc.setFillColor(...GREEN);
  doc.rect(0, 0, W, 34, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("TalentKenya", margin, 15);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("Kenya's trusted job marketplace · talentkenya.co.ke", margin, 22);
  doc.setFontSize(9);
  doc.setTextColor(200, 230, 210);
  doc.text("Official Offer Letter", W - margin, 15, { align: "right" });
  y = 46;

  // ── Reference line
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  const refNo = `TK-OFFER-${o.id.toUpperCase().slice(-8)}`;
  doc.text(`Reference: ${refNo}          Issued: ${o.createdAt}`, margin, y);
  y += 10;

  // ── Salutation & opening
  doc.setFontSize(11);
  doc.setTextColor(...DARK);
  doc.text(`Dear ${candidateName},`, margin, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  const opening = `We are pleased to extend the following offer of employment on behalf of ${o.company} for the position of ${o.title}. This offer is subject to the terms and conditions outlined below.`;
  const openingLines = doc.splitTextToSize(opening, contentW);
  doc.text(openingLines, margin, y);
  y += openingLines.length * 5.5 + 6;

  // ── Terms table
  const terms: [string, string][] = [
    ["Position", o.title],
    ["Employer", o.company],
    ["Monthly Salary", `KES ${o.amount.toLocaleString()} per month`],
    ["Start Date", o.start],
    ["Probation Period", o.probationMonths === "0" ? "None" : `${o.probationMonths} months`],
    ["Benefits & Terms", o.terms || "As per company policy"],
  ];
  const colLabel = 60;
  const rowH = 8.5;
  doc.setDrawColor(200, 200, 200);
  doc.setFillColor(...LIGHT);
  terms.forEach(([label, value], i) => {
    if (i % 2 === 0) { doc.setFillColor(247, 251, 248); } else { doc.setFillColor(255, 255, 255); }
    const labelDims = doc.getTextDimensions(doc.splitTextToSize(label, colLabel - 6));
    const valueDims = doc.getTextDimensions(doc.splitTextToSize(value, contentW - colLabel - 6));
    const textH = Math.max(labelDims.h, valueDims.h) + 3;
    const h = Math.max(rowH, textH);
    doc.rect(margin, y, contentW, h, "FD");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9.5);
    doc.setTextColor(...GRAY);
    doc.text(doc.splitTextToSize(label, colLabel - 6), margin + 3, y + h / 2 + 1, { baseline: "middle" });
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...DARK);
    doc.text(doc.splitTextToSize(value, contentW - colLabel - 6), margin + colLabel + 3, y + h / 2 + 1, { baseline: "middle" });
    y += h;
  });
  y += 7;

  // ── Conditions paragraph
  doc.setFontSize(10);
  const conditions = "This offer is conditional upon satisfactory reference checks and, where applicable, verification of professional credentials. You may accept these terms through your TalentKenya candidate portal. Should you wish to propose adjusted terms, use the negotiation feature in the portal; your proposal will be reviewed by the employer. If no response is received within 14 days of this letter's date, the offer lapses automatically.";
  const condLines = doc.splitTextToSize(conditions, contentW);
  doc.text(condLines, margin, y);
  y += condLines.length * 5 + 8;

  // ── Signatures
  doc.setDrawColor(...GRAY);
  doc.line(margin, y, margin + 60, y);
  doc.line(margin + 80, y, margin + 140, y);
  y += 4;
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  doc.text("For and on behalf of " + o.company, margin, y);
  doc.text("Candidate acknowledgment", margin + 80, y);

  // ── Footer
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text("Generated by TalentKenya · This is a simulated offer letter for demonstration purposes.", W / 2, 285, { align: "center" });

  doc.save(`offer-letter-${refNo.toLowerCase()}.pdf`);
}

export function fmtKESPdf(n: number) { return `KES ${n.toLocaleString()}`; }
