/* TalentKenya Resume Builder — compiles the candidate profile into a
   single-column ATS-friendly CV with a print stylesheet. */
import { Printer } from "lucide-react";
import { usePlatform } from "@/lib/platform";
import { PortalHeader } from "@/components/Layout";

export default function CandidateResumePage() {
  const { profile } = usePlatform();

  const print = () => window.print();

  return (
    <>
      <PortalHeader role="candidate" title="ATS resume builder" subtitle="A single-column, machine-readable CV. Export as PDF from your browser's print dialog."
        action={<button onClick={print} className="btn-press px-4 py-2 rounded-md bg-[#166534] text-white text-sm font-semibold flex items-center gap-1.5"><Printer className="h-4 w-4" /> Print / Save PDF</button>} />

      <div className="cv-paper bg-white rounded-lg border border-border p-8 md:p-12 max-w-3xl shadow-sm">
        <header className="border-b-2 border-black pb-4 mb-5">
          <h1 className="font-heading text-3xl font-bold uppercase tracking-tight">
            {profile.firstName || "First"} {profile.lastName || "Last"}
          </h1>
          <p className="text-sm font-semibold mt-1">{profile.title || "Professional title"}</p>
          <p className="text-xs text-gray-600 mt-2 flex flex-wrap gap-x-4 gap-y-1">
            {profile.email && <span>{profile.email}</span>}
            {profile.phone && <span>{profile.phone}</span>}
            {profile.town && <span>{profile.town}{profile.county ? `, ${profile.county}` : ""}</span>}
            {profile.linkedin && <span>{profile.linkedin}</span>}
          </p>
        </header>

        {profile.skills.length > 0 && (
          <section className="mb-5">
            <h2 className="text-xs font-bold uppercase tracking-widest border-b border-gray-300 pb-1 mb-2">Skills</h2>
            <p className="text-sm leading-relaxed">{profile.skills.join(" • ")}</p>
          </section>
        )}

        {profile.experience.length > 0 && (
          <section className="mb-5">
            <h2 className="text-xs font-bold uppercase tracking-widest border-b border-gray-300 pb-1 mb-2">Experience</h2>
            {profile.experience.map((e, i) => (
              <div key={i} className="mb-3">
                <div className="flex justify-between text-sm">
                  <span className="font-bold">{e.role || "Job title"}</span>
                  <span className="text-gray-600">{e.start}{e.end ? ` – ${e.end}` : ""}</span>
                </div>
                <p className="text-sm text-gray-700">{e.company || "Company"}</p>
                {e.achievements && <p className="text-sm text-gray-600 mt-1">{e.achievements}</p>}
              </div>
            ))}
          </section>
        )}

        {profile.education.length > 0 && (
          <section className="mb-5">
            <h2 className="text-xs font-bold uppercase tracking-widest border-b border-gray-300 pb-1 mb-2">Education</h2>
            {profile.education.map((e, i) => (
              <div key={i} className="mb-2 flex justify-between text-sm">
                <div>
                  <p className="font-bold">{e.degree}{e.field ? ` · ${e.field}` : ""}</p>
                  <p className="text-gray-600">{e.institution}</p>
                </div>
                <span className="text-gray-600">{e.year}</span>
              </div>
            ))}
          </section>
        )}

        {profile.skills.length === 0 && profile.experience.length === 0 && profile.education.length === 0 && (
          <p className="text-sm text-gray-500 text-center py-10">
            Your CV is empty. Add experience, education and skills in{" "}
            <a href="/candidate/profile" className="text-[#166534] font-semibold underline">your profile</a> to generate a complete CV.
          </p>
        )}

        <footer className="border-t border-gray-300 pt-3 mt-8 text-[10px] text-gray-500 flex justify-between">
          <span>Generated by TalentKenya ATS Resume Builder · Kenyan data protection compliant</span>
          <span>{new Date().toLocaleDateString("en-GB")}</span>
        </footer>
      </div>
    </>
  );
}
